# Generated by Django 5.1.5 on 2025-01-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagetranslation_webcamtranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTranslation',
        ),
        migrations.DeleteModel(
            name='VideoTranslation',
        ),
        migrations.DeleteModel(
            name='WebcamTranslation',
        ),
    ]
